model_name: opensearch
ignore:
  resource_names:
    - Package
    # - Domain
    - OutboundConnection
  field_paths:
    # SnapshotOptions is irrelevant for OpenSearch 5.3+
    - CreateDomainInput.SnapshotOptions
resources:
  Domain:
    renames:
      operations:
        CreateDomain:
          input_fields:
            DomainName: Name
            TagList: Tags
        DeleteDomain:
          input_fields:
            DomainName: Name
        DescribeDomain:
          input_fields:
            DomainName: Name
    reconcile:
      # Doing this because it takes a LONG time for the Domain's
      # endpoint/endpoints field to be populated, even after the Domain's
      # Processing field is set to False after creation...
      requeue_on_success_seconds: 60
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
      terminal_codes:
        - ValidationException
    #fields:
    #  AdvancedSecurityOptions.MasterUserOptions.MasterUserPassword:
    #    is_secret: true